/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Timestamp;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface AgCatalogAgGraph {
  graphid: number;
  name: string;
  namespace: string;
}

export interface AgCatalogAgLabel {
  graph: number;
  id: number | null;
  kind: string | null;
  name: string;
  relation: string;
  seq_name: string;
}

export interface Chunks {
  created_at: Generated<Timestamp>;
  embedding: string | null;
  id: Generated<string>;
  note_id: string;
  seq: number;
  text: string;
  token_count: number | null;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface Concepts {
  created_at: Generated<Timestamp>;
  description: string | null;
  embedding: string | null;
  id: Generated<string>;
  name: string;
  name_normalized: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface Conversations {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  title: string | null;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface Folders {
  cover_content: string | null;
  cover_hash: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  path: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface Links {
  created_at: Generated<Timestamp>;
  from_note_id: string;
  id: Generated<string>;
  raw_target: string;
  to_note_id: string | null;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface Memberships {
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  id: Generated<string>;
  role: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  workspace_id: string;
}

export interface Mentions {
  chunk_id: string;
  concept_id: string;
  id: Generated<string>;
  workspace_id: string;
}

export interface Messages {
  content: string | null;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  role: string;
  tool_call_id: string | null;
  tool_calls: Json | null;
  workspace_id: string;
}

export interface Notes {
  content: string | null;
  content_hash: string | null;
  created_at: Generated<Timestamp>;
  folder_id: string | null;
  id: Generated<string>;
  ingested_hash: string | null;
  path: string;
  pipeline: Generated<string>;
  status: Generated<string>;
  title: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface NotesGraphAgLabelEdge {
  end_id: string;
  id: Generated<string>;
  properties: Generated<string>;
  start_id: string;
}

export interface NotesGraphAgLabelVertex {
  id: Generated<string>;
  properties: Generated<string>;
}

export interface NoteTagDismissals {
  created_at: Generated<Timestamp>;
  note_id: string;
  tag_id: string;
  workspace_id: string;
}

export interface NoteTags {
  note_id: string;
  origin: string;
  tag_id: string;
  workspace_id: string;
}

export interface Notifications {
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<number>;
  is_active: Generated<boolean>;
  message: string;
  target_id: string | null;
  target_type: string;
  title: string;
  type: Generated<string>;
}

export interface ReadNotifications {
  id: Generated<number>;
  notification_id: number;
  read_at: Generated<Timestamp>;
  user_id: string;
}

export interface Relations {
  created_at: Generated<Timestamp>;
  description: string | null;
  from_concept_id: string;
  id: Generated<string>;
  to_concept_id: string;
  type: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface Sessions {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Sources {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  note_id: string;
  title: string | null;
  type: string | null;
  updated_at: Generated<Timestamp>;
  url: string;
  url_normalized: string;
  workspace_id: string;
}

export interface Tags {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  name_normalized: string;
  updated_at: Generated<Timestamp>;
  workspace_id: string;
}

export interface Todos {
  completed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  title: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  createdAt: Timestamp;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Timestamp;
}

export interface UserVerifications {
  createdAt: Timestamp | null;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Timestamp | null;
  value: string;
}

export interface Workspaces {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  accounts: Accounts;
  "ag_catalog.ag_graph": AgCatalogAgGraph;
  "ag_catalog.ag_label": AgCatalogAgLabel;
  chunks: Chunks;
  concepts: Concepts;
  conversations: Conversations;
  folders: Folders;
  links: Links;
  memberships: Memberships;
  mentions: Mentions;
  messages: Messages;
  note_tag_dismissals: NoteTagDismissals;
  note_tags: NoteTags;
  notes: Notes;
  "notes_graph._ag_label_edge": NotesGraphAgLabelEdge;
  "notes_graph._ag_label_vertex": NotesGraphAgLabelVertex;
  notifications: Notifications;
  read_notifications: ReadNotifications;
  relations: Relations;
  sessions: Sessions;
  sources: Sources;
  tags: Tags;
  todos: Todos;
  user_verifications: UserVerifications;
  users: Users;
  workspaces: Workspaces;
}
