/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Timestamp;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Memberships {
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  id: Generated<string>;
  role: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  workspace_id: string;
}

export interface Notifications {
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<number>;
  is_active: Generated<boolean>;
  message: string;
  target_id: string | null;
  target_type: string;
  title: string;
  type: Generated<string>;
}

export interface ReadNotifications {
  id: Generated<number>;
  notification_id: number;
  read_at: Generated<Timestamp>;
  user_id: string;
}

export interface Sessions {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Todos {
  completed: Generated<boolean>;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  title: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  createdAt: Timestamp;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Timestamp;
}

export interface UserVerifications {
  createdAt: Timestamp | null;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Timestamp | null;
  value: string;
}

export interface Workspaces {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  accounts: Accounts;
  memberships: Memberships;
  notifications: Notifications;
  read_notifications: ReadNotifications;
  sessions: Sessions;
  todos: Todos;
  user_verifications: UserVerifications;
  users: Users;
  workspaces: Workspaces;
}
